---
- hosts: all:!lb
  become: yes
  roles:
    - cleanup
    - common
    - kubenode


- hosts: lb
  become: yes
  roles:
    - common
    - haproxy

- hosts: masters
  become: yes
  roles:
    - master

- hosts: workers
  become: yes
  roles:
    - worker

# - hosts: all:!lb
#   become: yes
#   roles:
#     - upgrade-k8s

# - hosts: local
#   become: yes
#   roles:
#     - post-install