# ---
# - hosts: all:!lb
#   become: yes
#   roles:
#     - cleanup
#     - common

# # - hosts: lb
# #   become: yes
# #   roles:
# #     - haproxy

# - hosts: masters
#   become: yes
#   roles:
#     - master

# - hosts: workers
#   become: yes
#   roles:
#     - worker

# - hosts: all:!lb
#   become: yes
#   roles:
#     - upgrade-k8s