---
- name: remove containerd
  apt:
    name: containerd
    state: absent
- name: Cleanup node
  command: kubeadm reset -f cleanup-node
  ignore_errors: yes

- name: restart kubelet
  service:
    name: kubelet
    state: restarted
    enabled: yes
