---
- name: Cleanup node
  command: kubeadm reset cleanup-node -f 
  ignore_errors: yes

- name: Delete ~/.kube directory
  file:
    path: ~/.kube
    state: absent

- name: restart kubelet
  service:
    name: kubelet
    state: restarted
    enabled: yes
