---
- name: Update hostname
  hostname:
    name: "{{ hostname }}"

- name: Update /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts

- name: Update /etc/cloud/templates/hosts.debian.tmpl
  template:
    src: hosts.j2
    dest: /etc/cloud/templates/hosts.debian.tmpl
