- name: Update apt package index
  apt:
    update_cache: yes
- name: Create keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: remove old Kubernetes GPG key
  file:
    path: /etc/apt/keyrings/k8s.gpg
    state: absent

- name: Download Kubernetes GPG key
  shell: |
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/k8s.gpg
  args:
    creates: /etc/apt/keyrings/k8s.gpg

- name: Add Kubernetes repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/k8s.gpg] https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/deb/ /"
    state: present
    filename: kubernetes
    update_cache: yes

- name: Install new Kubernetes version
  apt:
    name:
      - kubeadm={{ kubernetes_version }}.2-1.1
    state: present
    allow_change_held_packages: yes
  when: inventory_hostname in groups['masters']

# upgrade master0

- name: Drain the node (only on control plane)
  command: >
    kubectl drain {{ inventory_hostname }} --ignore-daemonsets --delete-emptydir-data
  when: inventory_hostname == groups['masters'][0]

- name: Upgrade kubeadm
  command: kubeadm upgrade apply v{{ kubernetes_version }}.2 -y
  when: inventory_hostname == groups['masters'][0]

- name: Upgrade kubelet and kubectl
  apt:
    name:
      - kubelet={{ kubernetes_version }}.2-1.1
      - kubectl={{ kubernetes_version }}.2-1.1
    state: present
  when: inventory_hostname == groups['masters'][0]

- name: Restart kubelet
  systemd:
    name: kubelet
    state: restarted
    enabled: yes
  when: inventory_hostname == groups['masters'][0]

- name: Uncordon the node
  command: kubectl uncordon {{ inventory_hostname }}
  when: inventory_hostname == groups['masters'][0]

- name: Upgrade other masetr nodes
  command: kubeadm upgrade node
  when: inventory_hostname != groups['masters'][1]

# upgrade other workter nodes
- name: Upgrade kubelet and kubectl
  apt:
    name:
      - kubelet={{ kubernetes_version }}.2-1.1
      - kubectl={{ kubernetes_version }}.2-1.1
    state: present
    allow_change_held_packages: yes
  when: inventory_hostname != groups['masters'][0]

- name: Restart kubelet on other nodes
  systemd:
    name: kubelet
    state: restarted
    enabled: yes
  when: inventory_hostname != groups['masters'][0]