
- name: Generate control plane (master) join command
  shell: |
    cert_key=$(kubeadm init phase upload-certs --upload-certs | tail -1)
    join_cmd=$(kubeadm token create --print-join-command)
    echo "$join_cmd --control-plane --certificate-key $cert_key"
  register: master_join_output
  when: inventory_hostname == "kube-master-0"

- name: Generate worker join command
  shell: |
    kubeadm token create --print-join-command
  register: worker_join_output
  when: inventory_hostname == "kube-master-0"

- name: Store join commands
  set_fact:
    master_join_command: "{{ master_join_output.stdout }}"
    worker_join_command: "{{ worker_join_output.stdout }}"
  when: inventory_hostname == "kube-master-0"

- name: Join additional master nodes
  shell: "{{ hostvars['kube-master-0'].master_join_command }}"
  when: inventory_hostname in groups['new-masters']

- name: Join worker nodes
  shell: "{{ hostvars['kube-master-0'].worker_join_command }}"
  when: inventory_hostname in groups['new-workers']